name: Walter CI
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: "0 0 1 * *"
jobs:
  walter-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        # Workaround for this bug:
        # https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/58
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: piotr-yuxuan/walter-ci@main # use branch main
